apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "std.fullname" . }}-files
data:
{{ if .Values.config.filesGlob -}}
{{ (.Files.Glob .Values.config.filesGlob | indent 2 }}
{{ end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "std.fullname" . }}-env
data:
{{ range $k, $v := .Values.config.env -}}
  {{ $k | upper }}: {{ $v }}
{{ end -}}
