apiVersion: v1
kind: Secret
metadata:
  name: {{ template "std.fullname" . }}-files
type: Opaque
data:
{{ if .Values.secret.filesGlob -}}
{{ (.Files.Glob .Values.secret.filesGlob | indent 2 }}
{{ end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "std.fullname" . }}-env
data:
{{ range $k, $v := .Values.secret.env -}}
  {{ $k | upper }}: {{ $v | b64enc }}
{{ end -}}
